documentation:
  - changed-files:
    - any-glob-to-any-file:
      - docs/**/*
      - '*.md'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - go.mod
      - go.sum

build:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/*
      - Makefile
