{
 "title": "Desk Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Stand/Sit Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jarvis_desk_height:awake:7d", "legendFormat": "Week " },
    { "expr": "jarvis_desk_height:awake:1d", "legendFormat": "Day" }
   ]
  },
  {
   "title": "Stand/Sit Ratio over time, Avg. desk height",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum(jarvis_desk_height_meters > 0.2)\n    *\n    count(absent(macos_display_brightness_percent{state=\"asleep\"}))\n  )[24h:1m]\n)\n*\ncount(absent(macos_display_brightness_percent{state=\"asleep\"}))",
     "legendFormat": "Avg. Height (day)"
    },
    { "expr": "jarvis_desk_height:awake:1d", "legendFormat": "Stand/Sit Ratio (day)" },
    { "expr": "jarvis_desk_height:awake:7d", "legendFormat": "Stand/Sit Ratio (week)" }
   ]
  },
  {
   "title": "Desk Height",
   "type": "timeseries",
   "description": "Height of desk (when awake)",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "sum(jarvis_desk_height_meters > 0.2) * (count(absent(macos_display_brightness_percent{state=\"asleep\"})))",
     "legendFormat": "Desk Height"
    }
   ]
  },
  {
   "title": "Current state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jarvis_desk_height_meters > 0.2) * (count(absent(macos_display_brightness_percent{state=\"asleep\"})))"
    }
   ]
  },
  {
   "title": "Daily Trend",
   "type": "stat",
   "description": "Displays whether the daily ratio is greater than, equal, or less than the weekly ratio.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jarvis_desk_height:awake:1d) / max(jarvis_desk_height:awake:7d)",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Computer use over past 24hrs",
   "type": "stat",
   "description": "based on whether or not the display is awake",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n  count(macos_display_brightness_percent{state=\"awake\"})\n[24h:1m]) * 60"
    }
   ]
  },
  {
   "title": "Standing over past 24hrs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(jarvis_desk_height_meters > 0.2))\n*\nsum_over_time(\n  count(macos_display_brightness_percent{state=\"awake\"})\n[24h:1m])\n* 60"
    }
   ]
  },
  {
   "title": "Trends (deriv/1h)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(jarvis_desk_height:awake:1d[1h])",
     "legendFormat": "deriv(day)"
    },
    {
     "expr": "deriv(jarvis_desk_height:awake:7d[1h])",
     "legendFormat": "deriv(week)"
    }
   ]
  },
  {
   "title": "Stand/Sit Ratio over time, Avg. desk height",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(jarvis_desk_height:awake:1d[1d])",
     "legendFormat": "Stand/Sit (day)"
    }
   ]
  },
  {
   "title": "other stuff...",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Desk Height",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "targets": [
      { "expr": "jarvis_desk_height_meters", "legendFormat": "Desk Height" }
     ]
    },
    {
     "title": "Avg Desk Height (24hr while awake)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "targets": [
      {
       "expr": "avg_over_time(\n  (\n    sum(jarvis_desk_height_meters)\n    *\n    count(absent(macos_display_brightness_percent{state=\"asleep\"}))\n  )[24h:1m]\n)\n*\ncount(absent(macos_display_brightness_percent{state=\"asleep\"}))",
       "legendFormat": "24hr Avg. Desk Height"
      }
     ]
    },
    {
     "title": "Display Brightness over time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(macos_display_brightness_percent) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "awake time (past 24hrs)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum_over_time(\n  count(macos_display_brightness_percent{state=\"awake\"})\n[24h:1m])",
       "legendFormat": "Awake (past 24h)"
      }
     ]
    }
   ]
  }
 ]
}